n_iter: 15
n_particles: 2
timestamp: 0.1
run_graphing: true
nonblocking_graphing: true
run_plotting: true
simulation_properties:
- diffusion_coef: 3
- scenario_name: "turbulence-free"
- alpha: 0.666666667
- particle_speed: [5, 7]