n_iter: 100
n_particles: 2
timestamp: 0.1
run_graphing: true
run_plotting: true
nonblocking_graphing: true
simulation_properties:
- diffusion_coef: 3
- scenario_name: "turbulence-free"
- alpha: 0.666666667
- particle_speed: [0, 0]
- default_coords: [50, 50]